import http from 'node:http';
import {readFile,mkdir,writeFile,unlink} from 'node:fs/promises';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import worker from './worker/index.js';
await mkdir('.preview-data',{recursive:true});
const sqlite=new DatabaseSync('.preview-data/events.sqlite');
if(!sqlite.prepare("SELECT name FROM sqlite_master WHERE name='events'").get())sqlite.exec(await readFile('drizzle/0000_mute_taskmaster.sql','utf8'));
if(!sqlite.prepare("SELECT name FROM sqlite_master WHERE name='admin_credentials'").get())sqlite.exec(await readFile('drizzle/0001_volatile_gauntlet.sql','utf8'));
if(!sqlite.prepare("SELECT name FROM sqlite_master WHERE name='visits'").get())sqlite.exec(await readFile('drizzle/0002_soft_robbie_robertson.sql','utf8'));
if(!sqlite.prepare("SELECT name FROM sqlite_master WHERE name='guestbook'").get())sqlite.exec(await readFile('drizzle/0003_good_big_bertha.sql','utf8'));
if(!sqlite.prepare("PRAGMA table_info(guestbook)").all().some(c=>c.name==='password_hash'))sqlite.exec(await readFile('drizzle/0004_curly_sally_floyd.sql','utf8'));
if(!sqlite.prepare("SELECT name FROM sqlite_master WHERE name='guestbook_likes'").get())sqlite.exec(await readFile('drizzle/0005_orange_captain_britain.sql','utf8'));
const root=path.resolve('public');
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript','.mjs':'text/javascript','.wasm':'application/wasm','.jpg':'image/jpeg','.ttf':'font/ttf'};
const DB={prepare(sql){let values=[];return {bind(...args){values=args;return this},sql,get values(){return values}}},async batch(statements){sqlite.exec('BEGIN');try{const result=statements.map(s=>{const stmt=sqlite.prepare(s.sql);return /^\s*(SELECT|WITH)/i.test(s.sql)?{results:stmt.all(...s.values)}:{results:[],meta:stmt.run(...s.values)};});sqlite.exec('COMMIT');return result}catch(e){sqlite.exec('ROLLBACK');throw e}}};
const MEDIA={async put(key,bytes){const file=path.resolve('.preview-data/media',key);await mkdir(path.dirname(file),{recursive:true});await writeFile(file,bytes);},async get(key){try{return {body:await readFile(path.resolve('.preview-data/media',key))};}catch{return null;}},async delete(key){await unlink(path.resolve('.preview-data/media',key)).catch(()=>{});}};
const env={DB,MEDIA,ASSETS:{async fetch(request){const pathname=decodeURIComponent(new URL(request.url).pathname),file=path.resolve(root,'.'+pathname);if(!file.startsWith(root+path.sep))return new Response('Forbidden',{status:403});try{const bytes=await readFile(file);return new Response(request.method==='HEAD'?null:bytes,{headers:{'content-type':types[path.extname(file)]||'application/octet-stream'}})}catch{return new Response('Not found',{status:404})}}}};
http.createServer(async(q,r)=>{try{const chunks=[];let size=0;for await(const chunk of q){size+=chunk.length;if(size>4*1024*1024){r.writeHead(413);r.end();return}chunks.push(chunk)}const req=new Request('http://'+q.headers.host+q.url,{method:q.method,headers:q.headers,body:['GET','HEAD'].includes(q.method)?undefined:Buffer.concat(chunks)});const res=await worker.fetch(req,env);r.writeHead(res.status,Object.fromEntries(res.headers));r.end(Buffer.from(await res.arrayBuffer()))}catch(e){console.error(e);r.writeHead(500);r.end('Preview unavailable')}}).listen(4173,'0.0.0.0');
