import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFile} from 'node:fs/promises';
import worker from '../worker/index.js';
const sqlite=new DatabaseSync(':memory:');for(const file of ['0000_mute_taskmaster.sql','0001_volatile_gauntlet.sql','0002_soft_robbie_robertson.sql','0003_good_big_bertha.sql','0004_curly_sally_floyd.sql','0005_orange_captain_britain.sql'])sqlite.exec(await readFile('drizzle/'+file,'utf8'));
const DB={prepare(sql){let values=[];return {sql,bind(...args){values=args;return this},get values(){return values}}},async batch(statements){return statements.map(s=>{const stmt=sqlite.prepare(s.sql);return /^\s*(SELECT|WITH)/i.test(s.sql)?{results:stmt.all(...s.values)}:{results:[],meta:stmt.run(...s.values)}})}};
const env={DB,ASSETS:{fetch:()=>new Response('asset')}};
const request=(path,method='GET',data,cookie,origin='https://lab.test')=>worker.fetch(new Request('https://lab.test'+path,{method,headers:{...(cookie?{cookie}:{}),...(method==='POST'?{'content-type':'application/json',origin}:{})},...(method==='POST'?{body:JSON.stringify(data||{})}:{})}),env);
const cookie=r=>r.headers.get('set-cookie').split(';')[0];
assert.equal((await request('/api/admin/stats')).status,401);
assert.equal((await request('/api/admin/login','POST',{password:'incorrect'})).status,401);
const bootstrap=await request('/api/admin/login','POST',{password:'0000'});assert.equal(bootstrap.status,200);assert.equal((await bootstrap.clone().json()).mustChange,true);assert.match(bootstrap.headers.get('set-cookie'),/HttpOnly/);assert.match(bootstrap.headers.get('set-cookie'),/Secure/);
const oldCookie=cookie(bootstrap);assert.equal((await request('/api/admin/stats','GET',null,oldCookie)).status,403);
assert.equal((await request('/api/admin/password','POST',{password:'0000'},oldCookie)).status,400);
assert.equal((await request('/api/admin/password','POST',{password:'a-strong-test-password'},oldCookie,'https://evil.test')).status,403);
const password=crypto.randomUUID();const changed=await request('/api/admin/password','POST',{password},oldCookie);assert.equal(changed.status,200);const currentCookie=cookie(changed);
assert.equal((await request('/api/admin/stats','GET',null,oldCookie)).status,401);
assert.equal((await request('/api/admin/stats','GET',null,currentCookie)).status,200);
assert.equal((await request('/api/admin/login','POST',{password:'0000'})).status,401);
assert.equal((await request('/api/admin/login','POST',{password})).status,200);
assert.equal((await request('/api/admin/password','POST',{password:crypto.randomUUID(),currentPassword:'wrong'},currentCookie)).status,401);
await request('/api/admin/logout','POST',{},currentCookie);assert.equal((await request('/api/admin/stats','GET',null,currentCookie)).status,401);
const row=sqlite.prepare('SELECT * FROM admin_credentials').get();assert.notEqual(row.hash,password);assert.notEqual(row.hash,'0000');assert.equal(row.must_change,0);
for(let i=0;i<5;i++)await request('/api/admin/login','POST',{password:'wrong'});assert.equal((await request('/api/admin/login','POST',{password})).status,429);
const fresh=new DatabaseSync(':memory:');for(const file of ['0000_mute_taskmaster.sql','0001_volatile_gauntlet.sql'])fresh.exec(await readFile('drizzle/'+file,'utf8'));
const freshDB={prepare(sql){let values=[];return {sql,bind(...args){values=args;return this},get values(){return values}}},async batch(statements){return statements.map(s=>{const stmt=fresh.prepare(s.sql);return /^\s*(SELECT|WITH)/i.test(s.sql)?{results:stmt.all(...s.values)}:{results:[],meta:stmt.run(...s.values)}})}};
const publicEnv={...env,DB:freshDB,REQUIRE_ADMIN_BOOTSTRAP_SECRET:'true'},loginRequest=password=>new Request('https://public.test/api/admin/login',{method:'POST',headers:{'content-type':'application/json',origin:'https://public.test'},body:JSON.stringify({password})});
const originalError=console.error;console.error=()=>{};try{assert.equal((await worker.fetch(loginRequest('0000'),publicEnv)).status,503);}finally{console.error=originalError;}
assert.equal(fresh.prepare('SELECT COUNT(*) n FROM admin_credentials').get().n,0);
const initial=crypto.randomUUID();publicEnv.ADMIN_INITIAL_PASSWORD=initial;const secureLogin=await worker.fetch(loginRequest(initial),publicEnv);assert.equal(secureLogin.status,200);assert.equal((await secureLogin.json()).mustChange,true);assert.equal((await worker.fetch(loginRequest('0000'),publicEnv)).status,401);
console.log('PASS: public deployment requires an initial secret; managed-site credentials remain compatible.');
console.log('PASS: login gate, mandatory first password change, invalidation, logout, password hashing, origin guard, attempt limits.');
